# Generated by Django 4.1.7 on 2023-03-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default=0, max_length=200),
        ),
    ]
